export const ActionTypes = {
    FETCH__TOPPLACES:'FETCH__TOPPLACES',
    SET__TOPPLACES: 'SET__TOPPLACES',
    SELECTED__TOPPLACE: 'SELECTED__TOPPLACE',
    REMOVE__SELECTED__TOPPLACE:'REMOVE__SELECTED__TOPPLACE',

    FETCH__WHY__CHOOSE__US:'FETCH__WHY__CHOOSE__US',
    SET__WHY__CHOOSE__US:'SET__WHY__CHOOSE__US',

    FETCH__GUESTS__COMMENTS:'FETCH__GUESTS__COMMENTS',
    SET__GUESTS__COMMENTS:'SET__GUESTS__COMMENTS',

    FETCH__TOURS:'FETCH__TOURS',
    SET__TOURS:'SET__TOURS',
    SELECRED__TOUR:'SELECRED__TOUR',
    REMOVE__SELECTED__TOUR:'REMOVE__SELECTED__TOUR',

    FETCH__BLOG:"FETCH__BLOG",
    SET__BLOG:'SET__BLOG',
    SELECTED__BLOG: 'SELECTED__BLOG',
    REMOVE__SELECTED__BLOG:'REMOVE__SELECTED__BLOG',

    FETCH__ABOUT__KYRGYZSTAN:'FETCH__ABOUT__KYRGYZSTAN',
    SET__ABOUT__KYRGYZSTAN:'SET__ABOUT__KYRGYZSTAN',

    FETCH__OUR__STORY:'FETCH__OUR__STORY',
    SET__OUR__STORY:'SET__OUR__STORY',

    FETCH__OUR__MISSION:'FETCH__OUR__MISSION',
    SET__OUR__MISSION:'SET__OUR__MISSION',

    FETCH__TEAM__INFO:'FETCH__TEAM__INFO',
    SET__TEAM__INFO:'SET__TEAM__INFO',



    

}